name: RevertedSpawn
main: com.revertedsoft.RevertedSpawn
version: 0.1

commands:
  spawn:
    description: Returns the player to the spawn
    permission: RevertedSpawn.spawn
    usage: /spawn
    
  setspawn:
    description: Moves the spawn location
    permission: RevertedSpawn.setspawn
    usage: /setspawn
    
permissions:
  Reverted.spawn:
    description: Gives access to the /spawn command
    default: true
    
  Reverted.setspawn:
    description: Gives acces to the /setspawn command
    default: op